# This is a basic workflow to help you get started with Actions

name: test0701 

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "allinone"
  allinone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID }}
      TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
      CI_ENABLED: "true"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - uses: IvanJobs/AllInOneSample/teams-toolkit-cicd@v2
        with:
          operation-type: 'Build Teams App'
          project-root: ${{github.workspace}} 

      - name: Test The Project
        run: echo "do nothing"

      - uses: IvanJobs/AllInOneSample/teams-toolkit-cicd@v2
        with:
          operation-type: 'Provision Hosting Environment'
          project-root: ${{github.workspace}}

      - name: Validate Teams App Manifest
        run: teamsfx validate --verbose

      - name: Deploy in Azure
        run: teamsfx deploy

      - name: Pack Teams App
        run: teamsfx build
