# This is a basic workflow to help you get started with Actions

name: test0705 

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "allinone"
  allinone:
    # The type of runner that the job will run on
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [12]

    runs-on: ${{ matrix.os }}
    env:
      TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      TEST_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID }}
      TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
      CI_ENALBED: "true"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: OfficeDev/TeamsFx/packages/github-actions/teams-app-cicd@ruhe/action_toolkit_cicd 
        with:
          operation-type: 'Build Teams App'

      - name: Test The Project
        run: echo "do nothing"

      - uses: OfficeDev/TeamsFx/packages/github-actions/teams-app-cicd@ruhe/action_toolkit_cicd 
        with:
          operation-type: 'Provision Hosting Environment'

      - uses: OfficeDev/TeamsFx/packages/github-actions/teams-app-cicd@ruhe/action_toolkit_cicd 
        with:
          operation-type: 'Deploy to Hosting Environment'

      - uses: OfficeDev/TeamsFx/packages/github-actions/teams-app-cicd@ruhe/action_toolkit_cicd 
        with:
          operation-type: 'Validate Teams App Manifest'

      #- uses: IvanJobs/AllInOneSample@v3
      #  with:
      #    operation-type: 'Publish Teams App'
      #    project-root: ${{github.workspace}}
